spring.datasource.url=your_db_url
spring.datasource.username=your_username
spring.datasource.password=your_password
telegram.bot.token=your_bot_token

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.default-schema=public
spring.liquibase.drop-first=false

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect