spring.datasource.url=jdbc:postgresql://localhost:5432/telegram
spring.datasource.username=postgres
spring.datasource.password=1423
telegram.bot.token=8213540640:AAGi5qEZFMk4YPUEm92rCmA-LIIKzLJd2m0

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.default-schema=public
spring.liquibase.drop-first=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
